### ISSUE TITLE
1.6 compatibility

### ISSUE THREAD

**Issue by longd3** [floragunncom/search-guard#15]
Is the current version working with ES 1.6, are you planning to make it happen otherwise?

**Comment by mirandamon** [comment]
I think they said support will be coming soon...as of right now, I just tried running it with ES 1.6 and it didn't work.

**Comment by ap-ensighten** [comment]
@mirandamon  I was also going to try using with 1.6.   What errors or issues do you see with it?

**Comment by mirandamon** [comment]
@ap-ensighten 

Here is the error message I received when I did the initial setup and config for search-guard: 

{1.6.0}: Initialization Failed ...
- ExecutionError[java.lang.NoClassDefFoundError: org/elasticsearch/common/ContextHolder]
        NoClassDefFoundError[org/elasticsearch/common/ContextHolder]
                ClassNotFoundException[org.elasticsearch.common.ContextHolder]

**Comment by mirandamon** [comment]
@ap-ensighten Also, as of June 18, floragunncom said that we should stay tuned for a 1.6 compatibility update

**Comment by longd3** [comment]
I can't wait for this update!

**Comment by ap-ensighten** [comment]
@mirandamon Thanks for the info.

@floragunncom Do you have an update on when 1.6 compatibility will be available?

**Comment by otisg** [comment]
Another +1 for ES 1.6 support.

**Comment by longd3** [comment]
As a temporary solution, I am looking into http://nginx.com/resources/admin-guide/reverse-proxy/ and will never pay for Shield ...

**Comment by mirandamon** [comment]
@longd3 @ap-ensighten @otisg Many of the good, free plugins (i.e. https://github.com/salyh/elasticsearch-security-plugin) are no longer supported in the newer versions of elasticsearch. Search-guard is pretty much the only free option left!

**Comment by otisg** [comment]
@floragunncom maybe you can share your ETA for this so people know if they should wait, hack SG, issue PRs, look for alternatives, or something else.  Thanks.

**Comment by floragunncom** [comment]
This should now work with ES 1.6:
https://github.com/floragunncom/search-guard/tree/es1.6

**Comment by floragunncom** [comment]
@mirandamon Regarding https://github.com/floragunncom/search-guard/issues/15#issuecomment-115027193 pls. note that search guard is based on https://github.com/salyh/elasticsearch-security-plugin and elastic defender. Its more or less the official successor of these.

We're still in the process of boostrapping the product so please bear with us!

**Comment by lukewaite** [comment]
I'm attempting to test the aforementioned ES1.6 branch locally, but encountering the following error:
```
[2015-06-25 13:54:48,169][INFO ][node                     ] [Solarman] version[1.6.0], pid[17125], build[cdd3ac4/2015-06-09T13:36:34Z]
[2015-06-25 13:54:48,170][INFO ][node                     ] [Solarman] initializing ...
[2015-06-25 13:54:48,181][WARN ][plugins                  ] [Solarman] failed to load plugin from [file:/Users/lwaite/Development/elk/elasticsearch-1.6.0/plugins/search-guard/es-plugin.properties]
org.elasticsearch.ElasticsearchException: Failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:536)
	at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:411)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:116)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:154)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:77)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:245)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.NoClassDefFoundError: javassist/ClassPool
	at com.floragunn.searchguard.SearchGuardPlugin.<clinit>(SearchGuardPlugin.java:90)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:518)
	... 7 more
Caused by: java.lang.ClassNotFoundException: javassist.ClassPool
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 13 more
[2015-06-25 13:54:48,185][INFO ][plugins                  ] [Solarman] loaded [], sites [HQ]
```

The log from building the `es1.6` branch locally:
```
 ~/its-a-box/Projects/search-guard   es1.6  mvn package -DskipTests
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Search Guard 0.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ search-guard-16 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java) @ search-guard-16 ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ search-guard-16 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ search-guard-16 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 61 source files to /Users/lwaite/its-a-box/Projects/search-guard/target/classes
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/http/netty/SessionAwareNettyHttpChannel.java:[22,57] org.elasticsearch.common.netty.handler.codec.http.Cookie in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/http/netty/SessionAwareNettyHttpChannel.java:[24,57] org.elasticsearch.common.netty.handler.codec.http.DefaultCookie in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/util/SecurityUtil.java:[53,57] org.elasticsearch.common.netty.handler.codec.http.Cookie in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/util/SecurityUtil.java:[54,57] org.elasticsearch.common.netty.handler.codec.http.CookieDecoder in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] Cannot find annotation method 'value()' in type 'edu.umd.cs.findbugs.annotations.SuppressWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressWarnings not found
[WARNING] Cannot find annotation method 'justification()' in type 'edu.umd.cs.findbugs.annotations.SuppressWarnings'
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/http/netty/SessionAwareNettyHttpChannel.java:[58,23] org.elasticsearch.common.netty.handler.codec.http.Cookie in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/http/netty/SessionAwareNettyHttpChannel.java:[58,43] org.elasticsearch.common.netty.handler.codec.http.DefaultCookie in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/http/netty/SessionAwareNettyHttpChannel.java:[64,23] setDiscard(boolean) in org.elasticsearch.common.netty.handler.codec.http.Cookie has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/http/netty/SessionAwareNettyHttpChannel.java:[66,23] setMaxAge(int) in org.elasticsearch.common.netty.handler.codec.http.Cookie has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/authentication/http/clientcert/HTTPSClientCertAuthenticator.java:[54,26] sun.security.x509.X500Name is internal proprietary API and may be removed in a future release
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/authentication/http/clientcert/HTTPSClientCertAuthenticator.java:[58,47] sun.security.x509.X500Name is internal proprietary API and may be removed in a future release
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/util/SecurityUtil.java:[282,23] org.elasticsearch.common.netty.handler.codec.http.Cookie in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/util/SecurityUtil.java:[282,50] org.elasticsearch.common.netty.handler.codec.http.CookieDecoder in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/util/SecurityUtil.java:[287,23] org.elasticsearch.common.netty.handler.codec.http.Cookie in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/util/SecurityUtil.java:[287,40] org.elasticsearch.common.netty.handler.codec.http.Cookie in org.elasticsearch.common.netty.handler.codec.http has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/util/SecurityUtil.java:[288,59] getName() in org.elasticsearch.common.netty.handler.codec.http.Cookie has been deprecated
[WARNING] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/util/SecurityUtil.java:[289,34] getValue() in org.elasticsearch.common.netty.handler.codec.http.Cookie has been deprecated
[INFO] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/rest/AbstractACRestFilter.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/lwaite/its-a-box/Projects/search-guard/src/main/java/com/floragunn/searchguard/rest/AbstractACRestFilter.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ search-guard-16 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 23 resources
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ search-guard-16 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 20 source files to /Users/lwaite/its-a-box/Projects/search-guard/target/test-classes
[WARNING] Cannot find annotation method 'value()' in type 'edu.umd.cs.findbugs.annotations.SuppressWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressWarnings not found
[WARNING] Cannot find annotation method 'justification()' in type 'edu.umd.cs.findbugs.annotations.SuppressWarnings'
[INFO] /Users/lwaite/its-a-box/Projects/search-guard/src/test/java/com/floragunn/searchguard/AbstractUnitTest.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/lwaite/its-a-box/Projects/search-guard/src/test/java/com/floragunn/searchguard/AbstractUnitTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ search-guard-16 ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ search-guard-16 ---
[INFO] Building jar: /Users/lwaite/its-a-box/Projects/search-guard/target/search-guard-16-0.6-SNAPSHOT.jar
[INFO] 
[INFO] --- license-maven-plugin:1.8:download-licenses (download-licenses) @ search-guard-16 ---
[WARNING] POM for dependency net.sourceforge.spnego:spnego has an invalid license URL: null
[WARNING] POM for dependency org.apache.httpcomponents:fluent-hc has an invalid license URL: LICENSE.txt
[WARNING] POM for dependency org.apache.httpcomponents:httpasyncclient has an invalid license URL: LICENSE.txt
[WARNING] POM for dependency org.yaml:snakeyaml has an invalid license URL: LICENSE.txt
[INFO] 
[INFO] >>> maven-source-plugin:2.3:jar (attach-sources) > generate-sources @ search-guard-16 >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ search-guard-16 ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java) @ search-guard-16 ---
[INFO] 
[INFO] <<< maven-source-plugin:2.3:jar (attach-sources) < generate-sources @ search-guard-16 <<<
[INFO] 
[INFO] --- maven-source-plugin:2.3:jar (attach-sources) @ search-guard-16 ---
[INFO] Building jar: /Users/lwaite/its-a-box/Projects/search-guard/target/search-guard-16-0.6-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.4:single (default) @ search-guard-16 ---
[INFO] Reading assembly descriptor: /Users/lwaite/its-a-box/Projects/search-guard/src/main/assemblies/plugin.xml
[WARNING] The following patterns were never triggered in this artifact exclusion filter:
o  'org.elasticsearch:elasticsearch'

[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'com.floragunn:search-guard'

[INFO] Building zip: /Users/lwaite/its-a-box/Projects/search-guard/target/releases/search-guard-16-0.6-SNAPSHOT.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.085 s
[INFO] Finished at: 2015-06-25T13:38:27-04:00
[INFO] Final Memory: 40M/585M
[INFO] ------------------------------------------------------------------------
 ~/its-a-box/Projects/search-guard   es1.6  
```

**Comment by floragunncom** [comment]
How do you exactly installed the fresh build plugin?

**Comment by lukewaite** [comment]
Oops - sorry, I overlooked the release folder. Confirmed that fixes the issue. Thanks very much.

**Comment by madhusudand** [comment]
I am new to elasticsearch and safe guard. here i wanted to implement HTTPS for elasticsearch. i mean SSL/TLS communication between logstash elasticsearch .
 
i tried to install safe-guard plugin 
steps followed :
1) cloned code from https://github.com/floragunncom/search-guard.git
2)built using command mvn package -DskipTests
3)installed plugin using following command 
 " bin/plugin -u file:/root/madhu/elasticsearch-1.6.0/search-guard/target/releases/search-guard-0.6-SNAPSHOT.zip -i search-guard "


after that when i tried to run elasticsearch using  bin/elasticsearch i got this

"{1.6.0}: Initialization Failed ...
- ExecutionError[java.lang.NoClassDefFoundError: org/elasticsearch/common/ContextHolder]
        NoClassDefFoundError[org/elasticsearch/common/ContextHolder]
                ClassNotFoundException[org.elasticsearch.common.ContextHolder] "


please help me in this regard.


Thanks in advance.

**Comment by LinhTruongVan** [comment]
@madhusudand,
You must use "git clone -b es1.6 https://github.com/floragunncom/search-guard.git" instead of "git clone https://github.com/floragunncom/search-guard.git"

**Comment by madhusudand** [comment]
i used as u suggested.. but now i am getting this message when i start elasticsearch

[2015-06-30 16:38:03,322][INFO ][node                     ] [James Jaspers] version[1.6.0], pid[9669], build[cdd3ac4/2015-06-09T13:36:34Z]
[2015-06-30 16:38:03,323][INFO ][node                     ] [James Jaspers] initializing ...
[2015-06-30 16:38:03,628][INFO ][com.floragunn.searchguard.SearchGuardPlugin] Class enhancements for DLS/FLS successful
[2015-06-30 16:38:03,629][INFO ][plugins                  ] [James Jaspers] loaded [searchguard], sites []
[2015-06-30 16:38:03,680][INFO ][env                      ] [James Jaspers] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [29.5gb], net total_space [42.7gb], types [rootfs]
{1.6.0}: Initialization Failed ...
1) ElasticsearchException[You're trying to run elasticsearch as root or Windows Administrator and thats forbidden.]

**Comment by lukewaite** [comment]
@madhusudand 
For `You're trying to run elasticsearch as root or Windows Administrator and thats forbidden.` please see:
https://github.com/floragunncom/search-guard/issues/18
https://groups.google.com/forum/#!searchin/search-guard/root/search-guard/yAIrnlwNLsQ/8vouo5wMtAIJ

**Comment by lukewaite** [comment]
@floragunncom Perhaps we can close this issue? I think we can agree that 1.6 support is now working on the `es1.6` branch.

**Comment by LinhTruongVan** [comment]
@madhusudand 
To solve your new issue. You have to set "searchguard.check_for_root: false" in file elastisearch.yml of elasticsearch OR run elasticsearch with user who haven't admin privilege.

**Comment by loveczp** [comment]
@LinhTruongVan  give the right anwser!!!

**Comment by jandresaedo** [comment]
Hello guys,
       Any chance to fix this issue?. I can't install search-guard with ES 1.7
[2015-12-16 07:57:31,876][ERROR][bootstrap                ] Exception
org.elasticsearch.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/elasticsearch/common/ContextHolder
I can't pay for shield...


Thank you.
