### ISSUE TITLE
search-guard on ES 1.7

### ISSUE THREAD

**Issue by maoo** [floragunncom/search-guard#41]
Hi, 
I'm trying to get search-guard working on Elasticsearch 1.7, but I don't really understand which version to use.

Docs mention that ES 1.x versions should be working on master branch, however - using master branch (built with maven and manually installed) - I get

```
ExecutionError[java.lang.NoClassDefFoundError: org/elasticsearch/common/ContextHolder] NoClassDefFoundError[org/elasticsearch/common/ContextHolder] ClassNotFoundException[org.elasticsearch.common.ContextHolder] "
```

Using branch `es1.6` (following hints on https://github.com/floragunncom/search-guard/issues/15) I get

```
java.lang.NoSuchMethodException: org.elasticsearch.search.SearchService.setCallback(com.floragunn.searchguard.filter.level.SearchContextCallback)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at com.floragunn.searchguard.service.SearchGuardService.<init>(SearchGuardService.java:121)
....
```

and 

```
[2015-07-21 18:06:07,936][ERROR][bootstrap                ] [es1-centos-70] Exception
org.elasticsearch.ElasticsearchException: Wrong Elasticsearch version, this plugin only works with ES 1.6.x - Please download or build the correct plugin version which matches your Elasticsearch version.
        at com.floragunn.searchguard.service.SearchGuardService.checkVersion(SearchGuardService.java:237)
        at com.floragunn.searchguard.service.SearchGuardService.doStart(SearchGuardService.java:222)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85)
...
```

Full log file can be found on https://gist.github.com/maoo/5ab047bb9991168c71ce

I'd really like to test search-guard, is there any way I can work around it (apart from installing ES 1.6) ?

Thanks in advance.

**Comment by madhusudand** [comment]
Search guard for ES 1.7 is not yet released(not visible).There is no use in using SG1.6 for ES1.7 .
You should wait for them to come up with new stable code for 1.7.

**Comment by ld57** [comment]
well let s wait for next release :)

**Comment by remyderuysscher** [comment]
Me too. I cannot get this to work using master or any other 1.x branches.

**Comment by wiktor-kierzek** [comment]
can't wait to switch to ES 1.7, when do you expect to release search guard for newer ES?

**Comment by floragunncom** [comment]
next two weeks

**Comment by ld57** [comment]
Yes Yes Yes !!! :) (ok, another useless post)

**Comment by synaptics** [comment]
Hi, is this still on track or is it likely to slip?

**Comment by ld57** [comment]
Hi again Floragunncom,

by luck were you able to work on 1.7.1 support ? I cannot rollback to 1.6.2 :(

br

ld

**Comment by mz1991** [comment]
@floragunncom Are there any news? I still get the error: Class enhancements for DLS/FLS not successful due to javassist.CannotCompileException: [source error] no such field: context

**Comment by j0m** [comment]
hi there,
are there any chances for a 1.7 compatible version to be released soon?
sticking to 1.6 is somewhat unsatisfying...

best
O

**Comment by ld57** [comment]
Can we help ?

**Comment by bpesics** [comment]
+1

**Comment by atom992** [comment]
+1

**Comment by pdepaepe** [comment]
+1

**Comment by DavidEitzinger** [comment]
+1

**Comment by FrankVanDamme** [comment]
+1

**Comment by DPCollins** [comment]
+1

**Comment by MEPhoenyx** [comment]
Like everyone else , we also wait for a version that works with Elasticsearch 1.7 .

**Comment by pdepaepe** [comment]
ES 2 is coming soon, i think we can now ask for ES 2 support :)

**Comment by ld57** [comment]
Nah, we need both :)
Else we will need to chase other plugins owners to migrate their plugin to 2.0 :)
I do not know the impact of migrating ES 1.7.2 to ES 2.0 when out, it is a major upgrade, and concept and mechanism may change a lot, like not being free anymore :)

**Comment by TurboPunk** [comment]
+1

**Comment by madmaz** [comment]
+1

**Comment by jmaitrehenry** [comment]
+1

**Comment by dpasqualin** [comment]
Hello, sorry to bother, any news on this issue?

**Comment by ld57** [comment]
bah finally, ES 2.0 is out.

**Comment by dpasqualin** [comment]
Should the issue be updated to search-guard on ES 2.0? =P

**Comment by ulkas** [comment]
hi guys, i manage it working (didnt test it much for bugs) with manually compiling the source:
https://github.com/floragunncom/search-guard/issues/52#issuecomment-154404321

**Comment by jmaitrehenry** [comment]
Hi,

I made a fork of this project for support 1.7, and merge other PR like returning 403 instead of 500.
You can install it via bin/plugin -i com.petalmd/armor/1.7.0 or find it on github: https://github.com/petaldevelopment/armor

I’m using it in production and I’m working for having 2.0 on it soon.

I wish to add more option in futur.

Why I have not create a PR here? Because I think this project is dead (no comment from owner or commit from some time now) but if this project will be active again, I will be happy to create a merge request.

Thanks,
Julien

**Comment by ld57** [comment]
Thank you for your help Julien.
Maybe floragunncom is too busy for now, his work was nice, so bad for no news from him. 

I will migrate to elk 2.0 (cluster node method), but careful to all who will do that, lot of changes were made, in elasticsearch, and especially in logstash :)

I will test/use your 2.0 version with pleasure :)

**Comment by MobasherFasihy** [comment]
@jmaitrehenry But when i tried to install the package you said give bellow error and failed.
Ahmads-MacBook-Pro:elasticsearch-1.7.0 mobasherfasihy$ bin/plugin -i com.petalmd/armor/0.1
-> Installing com.petalmd/armor/0.1...
Trying http://download.elasticsearch.org/com.petalmd/armor/armor-0.1.zip...
Trying http://search.maven.org/remotecontent?filepath=com/petalmd/armor/0.1/armor-0.1.zip...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/com/petalmd/armor/0.1/armor-0.1.zip...
Trying https://github.com/com.petalmd/armor/archive/0.1.zip...
Trying https://github.com/com.petalmd/armor/archive/master.zip...
Failed to install com.petalmd/armor/0.1, reason: failed to download out of all possible locations..., use --verbose to get detailed information

**Comment by jmaitrehenry** [comment]
@MobasherFasihy, the version for es1.7 is 1.7.0, replace 0.1 by this version and it will work.

Envoyé de mon iPhone

**Comment by floragunncom** [comment]
Search Guard for Elasticsearch 2 is coming in Feb. 2016 and this project is not dead :-)

**Comment by floragunncom** [comment]
Search Guard for Elasticsearch 1.7.3 just released

<pre>
bin/plugin -i com.floragunn/search-guard/1.7.3.0
</pre>
