### ISSUE TITLE
Cannot Enable searchguard on ES 1.6.2

### ISSUE THREAD

**Issue by sdemircan** [floragunncom/search-guard#52]
Hi, 

I am trying get searchguard working on elasticsearch 1.6.2. I have installed it from es1.6 branch then used basic config at https://github.com/floragunncom/search-guard/blob/master/searchguard_config_example_1.yml.

When i start elasticsearch i see following errors on log:
```
[2015-08-31 18:12:03,581][ERROR][com.floragunn.searchguard.service.SearchGuardService] java.lang.NoSuchMethodException: org.elasticsearch.search.SearchService.setCallback(com.floragunn.searchguard.filter.level.SearchContextCallback)
java.lang.NoSuchMethodException: org.elasticsearch.search.SearchService.setCallback(com.floragunn.searchguard.filter.level.SearchContextCallback)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.floragunn.searchguard.service.SearchGuardService.<init>(SearchGuardService.java:121)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
	at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
	at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
	at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
	at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
	at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
	at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
	at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:59)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:212)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:77)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:245)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
[2015-08-31 18:15:44,280][INFO ][node                     ] [Scintilla] version[1.6.2], pid[21900], build[6220391/2015-07-29T09:24:47Z]
[2015-08-31 18:15:44,280][INFO ][node                     ] [Scintilla] initializing ...
[2015-08-31 18:15:44,616][ERROR][com.floragunn.searchguard.SearchGuardPlugin] Class enhancements for DLS/FLS not successful due to javassist.CannotCompileException: [source error] no such field: context
javassist.CannotCompileException: [source error] no such field: context
	at javassist.CtBehavior.insertAt(CtBehavior.java:1207)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1134)
	at com.floragunn.searchguard.SearchGuardPlugin.<clinit>(SearchGuardPlugin.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:518)
	at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:411)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:116)
	at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:159)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:77)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:245)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: compile error: no such field: context
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.JvstTypeChecker.atMethodArgs(JvstTypeChecker.java:221)
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:735)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:398)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:569)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1186)
	... 14 more
```

As i understand, it works on elasticsearch 1.6.x but I can not get searchguard to work with elasticsearch 1.6.2.

**Comment by floragunncom** [comment]
can you confirm that it works with 1.6.0?

**Comment by sdemircan** [comment]
It works with 1.6.0

```
[2015-09-01 10:24:58,846][INFO ][node                     ] [Kristoff von Doom] version[1.6.0], pid[19427], build[cdd3ac4/2015-06-09T13:36:34Z]
[2015-09-01 10:24:58,847][INFO ][node                     ] [Kristoff von Doom] initializing ...
[2015-09-01 10:24:59,132][INFO ][com.floragunn.searchguard.SearchGuardPlugin] Class enhancements for DLS/FLS successful
[2015-09-01 10:24:59,133][INFO ][plugins                  ] [Kristoff von Doom] loaded [searchguard], sites [head]
[2015-09-01 10:24:59,184][INFO ][env                      ] [Kristoff von Doom] using [1] data paths, mounts [[/ (/dev/xvda1)]], net usable_space [5.4gb], net total_space [7.7gb], types [ext4]
[2015-09-01 10:25:02,642][WARN ][com.floragunn.searchguard.util.SecurityUtil] AES 256 not supported, max key length for AES is 128. To enable AES 256 install 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files'
[2015-09-01 10:25:03,501][INFO ][node                     ] [Kristoff von Doom] initialized
[2015-09-01 10:25:03,505][INFO ][node                     ] [Kristoff von Doom] starting ...
[2015-09-01 10:25:03,673][INFO ][transport                ] [Kristoff von Doom] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.31.34.179:9300]}
[2015-09-01 10:25:03,712][INFO ][discovery                ] [Kristoff von Doom] elasticsearch/zXgN0O2WR3eSrVANHhrVcA
[2015-09-01 10:25:07,511][INFO ][cluster.service          ] [Kristoff von Doom] new_master [Kristoff von Doom][zXgN0O2WR3eSrVANHhrVcA][ip-172-31-34-179][inet[/172.31.34.179:9300]], reason: zen-disco-join (elected_as_master)
[2015-09-01 10:25:07,559][INFO ][http                     ] [Kristoff von Doom] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/172.31.34.179:9200]}
[2015-09-01 10:25:07,563][INFO ][node                     ] [Kristoff von Doom] started
[2015-09-01 10:25:07,611][INFO ][gateway                  ] [Kristoff von Doom] recovered [1] indices into cluster_state
```

**Comment by bilsch** [comment]
Any thoughts on this issue? Should we just run 1.6.0 for now?

**Comment by ld57** [comment]
maybe wait for 1.7.x ?

**Comment by ragogitpub** [comment]
I am new to Elasticsearch.

But I was looking at the code in SearchGuardPlugin.java where it is inserting the call using CtMethod.insertAt using line numbers. 

I am looking at the line numbers in SearchService at

https://github.com/elastic/elasticsearch/blob/4f7d813e2080443a32deb29c1da92f2ca92ce755/src/main/java/org/elasticsearch/search/SearchService.java
https://github.com/elastic/elasticsearch/blob/1.6/src/main/java/org/elasticsearch/search/SearchService.java
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/SearchService.java

And it seems the line number might not be the ideal way to insert the code. 

I was thinking using insertAfter might be more appropriate ? Also maybe using $1 ( for request ) and $_ ( for return value ) might be more appropriate ?

But again I am not familiar with elastic and hence I don't know what all those calls do ( parseTemplate/ dfsPhase.preProcess etc.

If they aren't relevant then maybe that line with insertAt can be replaced with the following ?

            me.insertAfter("if(callback != null) { try { callback.onCreateContext($_, $1); } catch ( Exception ex ) {} }");

**Comment by ulkas** [comment]
aint working on elastic `Version: 1.7.3, Build: 05d4530/2015-10-15T09:14:17Z, JVM: 1.7.0_79
` too

**Comment by floragunncom** [comment]
Search Guard for ES 1.7.3 released https://github.com/floragunncom/search-guard/tree/es1.7

**Comment by floragunncom** [comment]
can this issue be closed?

**Comment by floragunncom** [comment]
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!
